<?php /*NWJjbDNsYng1QmhMczU4UHdsd3hjSjdhdFViYVdVTi84eFR5dEl2NlNkNFl6VmkrQTZ0K0dWQ2llSkJPaXpLd0labS93dDcxRklpQ1RVR1BlNGlReTM3MWwrZm5JZ25SbFR6MlpXSktDRWFjdDUvejdxQ2dkN1pZNnVLZExtSElmUzRJNXlLY1BMZG1SYlUra3daYnZoZEFYVHBtOVQwRW9TUUI1U0U5eFNBPQ==*/
namespace GuzzleHttp\Exception;

class TransferException extends \RuntimeException implements GuzzleException
{
}
